<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:fn="http://www.w3.org/2005/xpath-functions"
  xmlns:dfdl="http://www.ogf.org/dfdl/dfdl-1.0/"
  xmlns:fakeTDL="urn:com.owlcyberdefense.fakeTDL">

  <xs:import namespace="urn:com.owlcyberdefense.fakeTDL" schemaLocation="fakeTDLType.dfdl.xsd"/>

  <xs:annotation>
    <xs:appinfo source="http://www.ogf.org/dfdl/">

      <dfdl:format  ref="fakeTDL:baseFormat" />

    </xs:appinfo>
  </xs:annotation>
  
  <xs:element name="fakeTDL" type="fakeTDL:fakeTDLType" dfdl:lengthKind="explicit" dfdl:length="64"/>

  <xs:element name="fakeTDLFile">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fakeTDL" type="fakeTDL:fakeTDLType" dfdl:lengthKind="explicit" dfdl:length="64"
                 minOccurs="1" maxOccurs="100" dfdl:occursCountKind="implicit">
          <xs:annotation><xs:appinfo source="http://www.ogf.org/dfdl/">
           
            <dfdl:discriminator testKind="pattern" testPattern="."/>
          </xs:appinfo></xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
